export default () => ({
   'team-representative': 'Panel reprezentanta',
   'league-organizer': 'Panel organizatora',
   'user-profile': 'Profil użytkownika',
   'create-league': 'Utwórz ligę',
   'create-team': 'Utwórz zespół',
   'team-composition': 'Skład zespołu',
   'league-schedule': 'Terminarz ligi',
   'team-match-schedule': 'Terminarz rozgrywek',
   'league-manage': 'Zarządzanie ligą',
   'league-standing': 'Tabela ligowa',
   'league-statistics': 'Statystyki',
   player: 'Zawodnik',
   league: 'Liga',
   leagues: 'Ligi',
   teams: 'Zespoły',
   overview: 'Informacje',
   statistics: 'Statystyki',
   stadium: 'Stadion',
   match: 'Mecz',
});
